lint

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -67,7 +67,7 @@ install_deno() {
   (
     echo "∗ Downloading and installing deno..."
     curl --silent --location --create-dirs --output "$source_path" "$download_url" || fail "Could not download"
-    $uncompress_command $source_path || fail "Could not uncompress"
+    $uncompress_command "$source_path" || fail "Could not uncompress"
     chmod +x "${install_path}/bin/deno" || fail "Could not find uncompressed binary"
     echo "The installation was successful!"
   ) || (
